# Dictionary of expressions to be replaced by their respective abbreviations.
# The second value of the tuple is the replace chance
abbr_list = {"as far as i know": ('afaik', 2),
             "as soon as possible": ('asap', 3),
             "by the way": ('btw', 4),
             "be right back": ('brb', 3),
             "direct message": ('dm', 2),
             "for your information": ('fyi', 3),
             "oh my god": ('omg', 3),
             "good morning": ('gm', 2),
             "good night": ('gn', 3),
             "i know right": ('ikr', 4),
             "i do not know": ('idk', 4),
             "in my opinion": ('imo', 4),
             "i love you": ('ily', 4),
             "in real life": ('irl', 2),
             "just kidding": ('jk', 3),
             "message": ('msg', 3),
             "nevermind": ('nvm', 3),
             "no problem": ('np', 4),
             "shaking my head": ('idk', 4),
             "probably": ('probs', 2),
             "right now": ('rn', 3),
             "thank you": ('ty', 4),
             "that feeling when": ('tfw', 4),
             "to be honest": ('tbh', 3),
             "to be fair": ('tbf', 3),
             "what is up": ('sup', 2)}

enders_list = {"lol": 4,
               "lmao": 3,
               "haha": 4,
               "hehe": 2,
               "wtf": 3,
               "smh": 2,
               "imo": 2,
               "omg": 2,
               "wow": 2,
               "xD": 3,
               ":)": 5,
               ";)": 2,
               "=)": 1,
               ":P": 1,
               "^^": 2,
               "o_O": 1}

starters_list = {"Imo": 3,
                 "Afaik": 2,
                 "Btw": 4,
                 "Fyi": 3,
                 "Omg": 2,
                 "Tfw": 3,
                 "Tbh": 3,
                 "Tbf": 2,
                 "Wow": 3,
                 "Fun fact: ": 1,
                 "-->": 1}
