# Dictionary of expressions to be replaced by their respective abbreviations.
# The second value of the tuple is the replace chance
abbr_list = {"as far as i know": ('afaik', 4),
             "as soon as possible": ('asap', 6),
             "by the way": ('btw', 8),
             "be right back": ('brb', 6),
             "direct message": ('dm', 4),
             "for your information": ('fyi', 6),
             "oh my god": ('omg', 6),
             "good morning": ('gm', 4),
             "good night": ('gn', 6),
             "i know right": ('ikr', 8),
             "i do not know": ('idk', 8),
             "in my opinion": ('imo', 8),
             "i love you": ('ily', 8),
             "in real life": ('irl', 4),
             "just kidding": ('jk', 6),
             "message": ('msg', 6),
             "nevermind": ('nvm', 6),
             "no problem": ('np', 8),
             "shaking my head": ('idk', 8),
             "probably": ('probs', 4),
             "right now": ('rn', 6),
             "thank you": ('ty', 8),
             "that feeling when": ('tfw', 8),
             "to be honest": ('tbh', 6),
             "to be fair": ('tbf', 6),
             "what is up": ('sup', 4),
             "to": ('2', 4),
             "for": ('4', 4),
             "are": ('r', 6),
             "you": ('u', 8),
             "your": ('ur', 8),
             "you are": ('ur', 6),
             "going to": ('gonna', 8),
             "want to": ('wanna', 8),
             "kind of": ('kinda', 8),
             "though": ('tho', 8),
             "yes": ('yup', 6)}

enders_list = {"lol": 4,
               "lmao": 3,
               "haha": 7,
               "hehe": 2,
               "wtf": 3,
               "smh": 1,
               "imo": 2,
               "omg": 2,
               "wow": 2,
               "xD": 4,
               ":)": 9,
               ";)": 7,
               "=)": 5,
               ":P": 3,
               "^^": 6,
               "o_O": 1}

starters_list = {"Imo": 3,
                 "Afaik": 2,
                 "Btw,": 4,
                 "Fyi,": 3,
                 "OMG!": 2,
                 "Tfw": 3,
                 "Tbh,": 3,
                 "Tbf,": 2,
                 "Wow,": 3,
                 "Fun fact:": 1,
                 "-->": 1}
